version: '3'
services:
  student_server:
    build:
      context: ./server
    image: student_server
    restart: always
    ports:
      - "44444:44444"
    env_file:
      - ./server/laravel/.env
    volumes:
      - ./server/secret/:/etc/gcp/
      - ./server/laravel/:/var/www/html/:rw
    command: ["php", "-S", "0.0.0.0:44444", "-t", "public/"]
    depends_on:
      - cloudsql
    networks:
      - ddl_default

  student_client:
    build:
      context: ./client
    image: student_client
    restart: always
    ports:
      - "33333:3000"
    volumes:
      - ./client/src:/app/src:rw
      - ./client/public:/app/public:rw
      - ./client/.prettierrc:/app/.prettierrc:rw
      - ./client/package.json:/app/package.json:rw
      - ./client/yarn.lock:/app/yarn.lock:rw
      - ./client/tsconfig.json:/app/tsconfig.json:rw
    command: [start]

  cloudsql:
    build:
      context: ./mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: always
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: school_system

networks:
  ddl_default:
    external: true